apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-service
    helm.sh/chart: {{ include "dragonchain-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: dragonchain
    app.kubernetes.io/component: webserver
    app.kubernetes.io/version: {{ .Values.dragonchain.image.version }}
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      targetPort: 8080
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
      {{ else }}
      port: 80
      {{ end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-webserver
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cr-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cr-service
    helm.sh/chart: {{ include "dragonchain-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: dragonchain
    app.kubernetes.io/component: cacheredis
    app.kubernetes.io/version: {{ .Values.dragonchain.image.version }}
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-cacheredis
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pr-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-pr-service
    helm.sh/chart: {{ include "dragonchain-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: dragonchain
    app.kubernetes.io/component: persistent-redis
    app.kubernetes.io/version: {{ .Values.dragonchain.image.version }}
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-persistent-redis
    dragonchainId: {{ .Values.global.environment.INTERNAL_ID }}
