node_id: 31ce807a-868c-11e6-99f6-3c970e3bee11
owner: OWNER
business: BUSINESS
deploy_location: SEATTLE

# dictionary of public transmission flags (BitCoin, LiteCoin, etc...)
public_transmission:â€¨
    p1_pub_trans: off
    p2_pub_trans: on
    p3_pub_trans: off
    p4_pub_trans: off

# host:port:id:phases
# phase 1 = 00001
# phase 2 = 00011 ...
peers:
    - localhost:8081:8f0aabca-aa2e-4aab-a1d2-8420ffba0cce:00010
    - localhost:8082:0318edaf-4a08-49c9-ba03-c4d732fd8d9c:00011
    - localhost:8083:f9aba210-1d66-4d06-80d6-e87895c8da00:00010
    - localhost:8084:4cc5d599-df17-4c4a-8f3c-2ce70f874c54:00010